// "PublicCode" is the bus line for public use
const busLines = [
  {
    Id: "99",
    Name: "Mission - Decoto - Fremont Blvd.",
    TransportMode: "bus",
    PublicCode: "99",
    SiriLineRef: "99",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "51B",
    Name: "University - College - Rockridge",
    TransportMode: "bus",
    PublicCode: "51B",
    SiriLineRef: "51B",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "210",
    Name: "Fremont Blvd. - Mission San Jose",
    TransportMode: "bus",
    PublicCode: "210",
    SiriLineRef: "210",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "54",
    Name: "35th Ave. - Merritt College",
    TransportMode: "bus",
    PublicCode: "54",
    SiriLineRef: "54",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "51A",
    Name: "Broadway - Santa Clara",
    TransportMode: "bus",
    PublicCode: "51A",
    SiriLineRef: "51A",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "45",
    Name: "Seminary - Sobrante Park",
    TransportMode: "bus",
    PublicCode: "45",
    SiriLineRef: "45",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "840",
    Name: "Foothill - Eastmont All Nighter",
    TransportMode: "bus",
    PublicCode: "840",
    SiriLineRef: "840",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "93",
    Name: "Ashland - San Lorenzo - A St.",
    TransportMode: "bus",
    PublicCode: "93",
    SiriLineRef: "93",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "95",
    Name: "D St. - Maud - Fairview",
    TransportMode: "bus",
    PublicCode: "95",
    SiriLineRef: "95",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "251",
    Name: "Paseo Padre - Thornton - Cherry",
    TransportMode: "bus",
    PublicCode: "251",
    SiriLineRef: "251",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "J",
    Name: "Sacramento -  Christie Transbay",
    TransportMode: "bus",
    PublicCode: "J",
    SiriLineRef: "J",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "L",
    Name: "San Pablo Transbay",
    TransportMode: "bus",
    PublicCode: "L",
    SiriLineRef: "L",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "98",
    Name: "Eastmont - 98th Ave. - Edgewater",
    TransportMode: "bus",
    PublicCode: "98",
    SiriLineRef: "98",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "F",
    Name: "Adeline - Market Transbay",
    TransportMode: "bus",
    PublicCode: "F",
    SiriLineRef: "F",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "57",
    Name: "40th St. - MacArthur",
    TransportMode: "bus",
    PublicCode: "57",
    SiriLineRef: "57",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "88",
    Name: "Sacramento - Market",
    TransportMode: "bus",
    PublicCode: "88",
    SiriLineRef: "88",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "21",
    Name: "Dimond - Fruitvale - Bay Farm",
    TransportMode: "bus",
    PublicCode: "21",
    SiriLineRef: "21",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "62",
    Name: "7th St. - San Antonio - 23rd Av.",
    TransportMode: "bus",
    PublicCode: "62",
    SiriLineRef: "62",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "40",
    Name: "Foothill - Bancroft - Bay Fair",
    TransportMode: "bus",
    PublicCode: "40",
    SiriLineRef: "40",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "G",
    Name: "Colusa - Solano Transbay",
    TransportMode: "bus",
    PublicCode: "G",
    SiriLineRef: "G",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "65",
    Name: "Grizzly Peak - Euclid",
    TransportMode: "bus",
    PublicCode: "65",
    SiriLineRef: "65",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "7",
    Name: "Arlington - 1000 Oaks - Shattuck",
    TransportMode: "bus",
    PublicCode: "7",
    SiriLineRef: "7",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "72M",
    Name: "Macdonald - San Pablo",
    TransportMode: "bus",
    PublicCode: "72M",
    SiriLineRef: "72M",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "LA",
    Name: "Hilltop - Pierce Transbay",
    TransportMode: "bus",
    PublicCode: "LA",
    SiriLineRef: "LA",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "216",
    Name: "Niles - Stevenson - NewPark",
    TransportMode: "bus",
    PublicCode: "216",
    SiriLineRef: "216",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "239",
    Name: "Grimmer - Warm Springs",
    TransportMode: "bus",
    PublicCode: "239",
    SiriLineRef: "239",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "NX",
    Name: "Grand Lake - Laurel  Transbay",
    TransportMode: "bus",
    PublicCode: "NX",
    SiriLineRef: "NX",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "376",
    Name: "Cutting - North Richmond Nights",
    TransportMode: "bus",
    PublicCode: "376",
    SiriLineRef: "376",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "39",
    Name: "Skyline - Dimond - Fruitvale",
    TransportMode: "bus",
    PublicCode: "39",
    SiriLineRef: "39",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "O",
    Name: "Santa Clara - Encinal Transbay",
    TransportMode: "bus",
    PublicCode: "O",
    SiriLineRef: "O",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "P",
    Name: "Piedmont - Oakland Ave. Transbay",
    TransportMode: "bus",
    PublicCode: "P",
    SiriLineRef: "P",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "U",
    Name: "Stanford - Dumbarton - Fremont",
    TransportMode: "bus",
    PublicCode: "U",
    SiriLineRef: "U",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "W",
    Name: "High - South Shore Transbay",
    TransportMode: "bus",
    PublicCode: "W",
    SiriLineRef: "W",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "800",
    Name: "Rich - Oak Transbay All Nighter",
    TransportMode: "bus",
    PublicCode: "800",
    SiriLineRef: "800",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "60",
    Name: "CSUEB - Southland - Chabot Coll",
    TransportMode: "bus",
    PublicCode: "60",
    SiriLineRef: "60",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "14",
    Name: "14th St - San Antonio - High St",
    TransportMode: "bus",
    PublicCode: "14",
    SiriLineRef: "14",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "67",
    Name: "Tilden Park - Spruce - Oxford",
    TransportMode: "bus",
    PublicCode: "67",
    SiriLineRef: "67",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "802",
    Name: "San Pablo All Nighter",
    TransportMode: "bus",
    PublicCode: "802",
    SiriLineRef: "802",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "851",
    Name: "College - Broadway All Nighter",
    TransportMode: "bus",
    PublicCode: "851",
    SiriLineRef: "851",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "V",
    Name: "Montclair - Park Blvd. Transbay",
    TransportMode: "bus",
    PublicCode: "V",
    SiriLineRef: "V",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "NL",
    Name: "MacArthur Transbay Limited",
    TransportMode: "bus",
    PublicCode: "NL",
    SiriLineRef: "NL",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "212",
    Name: "Fremont Blvd. - Pacific Commons",
    TransportMode: "bus",
    PublicCode: "212",
    SiriLineRef: "212",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "217",
    Name: "Mission San Jose - Milpitas",
    TransportMode: "bus",
    PublicCode: "217",
    SiriLineRef: "217",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "18",
    Name: "Solano - Shattuck - MLK Jr.",
    TransportMode: "bus",
    PublicCode: "18",
    SiriLineRef: "18",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "1T",
    Name: "Uptown Oakland\\ San Leandro BART Southbound OWL",
    TransportMode: "bus",
    PublicCode: "1T",
    SiriLineRef: "",
    Monitored: false,
    OperatorRef: "AC",
  },
  {
    Id: "52",
    Name: "UC Village - Cedar - UC Campus",
    TransportMode: "bus",
    PublicCode: "52",
    SiriLineRef: "52",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "19",
    Name: "Buena Vista - Fruitvale",
    TransportMode: "bus",
    PublicCode: "19",
    SiriLineRef: "19",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "200",
    Name: "Decoto - Newark Blvd. - Mowry",
    TransportMode: "bus",
    PublicCode: "200",
    SiriLineRef: "200",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "20",
    Name: "Dimond - Fruitvale - South Shore",
    TransportMode: "bus",
    PublicCode: "20",
    SiriLineRef: "20",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "46L",
    Name: "82nd Ave. - Grass Valley Limited",
    TransportMode: "bus",
    PublicCode: "46L",
    SiriLineRef: "46L",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "FS",
    Name: "Shattuck - University Transbay",
    TransportMode: "bus",
    PublicCode: "FS",
    SiriLineRef: "FS",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "215",
    Name: "Osgood - Warm Springs - Landing",
    TransportMode: "bus",
    PublicCode: "215",
    SiriLineRef: "215",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "604",
    Name: "Head Royce - Hebrew Day - Berk.",
    TransportMode: "bus",
    PublicCode: "604",
    SiriLineRef: "604",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "607",
    Name: "Richmond High - Point Richmond",
    TransportMode: "bus",
    PublicCode: "607",
    SiriLineRef: "607",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "232",
    Name: "Mission - Decoto - NewPark",
    TransportMode: "bus",
    PublicCode: "232",
    SiriLineRef: "232",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "605",
    Name: "Head Royce - Montclair - College",
    TransportMode: "bus",
    PublicCode: "605",
    SiriLineRef: "605",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "606",
    Name: "Head Royce - Piedmont",
    TransportMode: "bus",
    PublicCode: "606",
    SiriLineRef: "606",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "611",
    Name: "Westlake Middle - 14th Ave.",
    TransportMode: "bus",
    PublicCode: "611",
    SiriLineRef: "611",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "617",
    Name: "Skyline High - Seminary",
    TransportMode: "bus",
    PublicCode: "617",
    SiriLineRef: "617",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "646",
    Name: "Montera - Skyline - 82nd Ave.",
    TransportMode: "bus",
    PublicCode: "646",
    SiriLineRef: "646",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "34",
    Name: "Estudillo - Davis - Meekland",
    TransportMode: "bus",
    PublicCode: "34",
    SiriLineRef: "34",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "35",
    Name: "Estudillo - Davis -  Lewelling",
    TransportMode: "bus",
    PublicCode: "35",
    SiriLineRef: "35",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "41",
    Name: "Whitman - Huntwood - Union Landg",
    TransportMode: "bus",
    PublicCode: "41",
    SiriLineRef: "41",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "56",
    Name: "Santa Clara - Weekes - Huntwood",
    TransportMode: "bus",
    PublicCode: "56",
    SiriLineRef: "56",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "648",
    Name: "Skyline - Comm. Day - High St.",
    TransportMode: "bus",
    PublicCode: "648",
    SiriLineRef: "648",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "649",
    Name: "Montera - Skyline - Grass Valley",
    TransportMode: "bus",
    PublicCode: "649",
    SiriLineRef: "649",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "6",
    Name: "Berkeley - Telegraph - Oakland",
    TransportMode: "bus",
    PublicCode: "6",
    SiriLineRef: "6",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "650",
    Name: "Montera - Oakmore - Seminary",
    TransportMode: "bus",
    PublicCode: "650",
    SiriLineRef: "650",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "652",
    Name: "Skyline High - Elmhurst",
    TransportMode: "bus",
    PublicCode: "652",
    SiriLineRef: "652",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "653",
    Name: "Montera - MacArthur",
    TransportMode: "bus",
    PublicCode: "653",
    SiriLineRef: "653",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "620",
    Name: "Newark Jr. High - Cedar",
    TransportMode: "bus",
    PublicCode: "620",
    SiriLineRef: "620",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "621",
    Name: "American High - Thornton Jr.",
    TransportMode: "bus",
    PublicCode: "621",
    SiriLineRef: "621",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "623",
    Name: "Irvington High - Horner Jr. High",
    TransportMode: "bus",
    PublicCode: "623",
    SiriLineRef: "623",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "654",
    Name: "Skyline High - 35th Ave.",
    TransportMode: "bus",
    PublicCode: "654",
    SiriLineRef: "654",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "10",
    Name: "E. 14th St. - Mission",
    TransportMode: "bus",
    PublicCode: "10",
    SiriLineRef: "10",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "624",
    Name: "Mission San Jose - Hopkins Jr.",
    TransportMode: "bus",
    PublicCode: "624",
    SiriLineRef: "624",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "625",
    Name: "Washington - Centerville Jr.",
    TransportMode: "bus",
    PublicCode: "625",
    SiriLineRef: "625",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "626",
    Name: "Newark Memorial - Newark Blvd.",
    TransportMode: "bus",
    PublicCode: "626",
    SiriLineRef: "626",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "628",
    Name: "Newark Memorial  - Cedar",
    TransportMode: "bus",
    PublicCode: "628",
    SiriLineRef: "628",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "629",
    Name: "Newark Memorial - Cherry - Haley",
    TransportMode: "bus",
    PublicCode: "629",
    SiriLineRef: "629",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "631",
    Name: "Encinal - Alameda - Bay Farm",
    TransportMode: "bus",
    PublicCode: "631",
    SiriLineRef: "631",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "638",
    Name: "Skyline High - 73rd Ave.",
    TransportMode: "bus",
    PublicCode: "638",
    SiriLineRef: "638",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "642",
    Name: "Montera - Montclair - Colton",
    TransportMode: "bus",
    PublicCode: "642",
    SiriLineRef: "642",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "655",
    Name: "Montera - 35th Ave.",
    TransportMode: "bus",
    PublicCode: "655",
    SiriLineRef: "655",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "657",
    Name: "Oak High - Oak Tech - MacArthur",
    TransportMode: "bus",
    PublicCode: "657",
    SiriLineRef: "657",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "801",
    Name: "E 14th - Mission  All Nighter",
    TransportMode: "bus",
    PublicCode: "801",
    SiriLineRef: "801",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "86",
    Name: "Winton - Industrial - Tennyson",
    TransportMode: "bus",
    PublicCode: "86",
    SiriLineRef: "86",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "805",
    Name: "MacArthur - Airport All Nighter",
    TransportMode: "bus",
    PublicCode: "805",
    SiriLineRef: "805",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "71",
    Name: "Parchester - Rumrill - Carlson",
    TransportMode: "bus",
    PublicCode: "71",
    SiriLineRef: "71",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "74",
    Name: "San Pablo Dam - 23rd St.",
    TransportMode: "bus",
    PublicCode: "74",
    SiriLineRef: "74",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "72",
    Name: "Hilltop - CCC - San Pablo",
    TransportMode: "bus",
    PublicCode: "72",
    SiriLineRef: "72",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "90",
    Name: "85th Ave. - Elmhurst - 90th Ave.",
    TransportMode: "bus",
    PublicCode: "90",
    SiriLineRef: "90",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "97",
    Name: "Hesperian - Alvarado - Decoto",
    TransportMode: "bus",
    PublicCode: "97",
    SiriLineRef: "97",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "73",
    Name: "73rd Ave. - Coliseum - Airport",
    TransportMode: "bus",
    PublicCode: "73",
    SiriLineRef: "73",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "658",
    Name: "Skyline - Bret Harte - MacArthur",
    TransportMode: "bus",
    PublicCode: "658",
    SiriLineRef: "658",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "660",
    Name: "Montera - Broadway Terrace",
    TransportMode: "bus",
    PublicCode: "660",
    SiriLineRef: "660",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "662",
    Name: "Skyline High - Broadway Terrace",
    TransportMode: "bus",
    PublicCode: "662",
    SiriLineRef: "662",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "663",
    Name: "Encinal - South Shore - High St.",
    TransportMode: "bus",
    PublicCode: "663",
    SiriLineRef: "663",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "667",
    Name: "Korematsu - E.C. - No. Richmond",
    TransportMode: "bus",
    PublicCode: "667",
    SiriLineRef: "667",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "669",
    Name: "Crespi Middle - San Pablo Dam",
    TransportMode: "bus",
    PublicCode: "669",
    SiriLineRef: "669",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "671",
    Name: "De Anza - Crespi - Fairmede",
    TransportMode: "bus",
    PublicCode: "671",
    SiriLineRef: "671",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "672",
    Name: "Crespi - Hiltop - Broadway",
    TransportMode: "bus",
    PublicCode: "672",
    SiriLineRef: "672",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "12",
    Name: "MLK Jr. - Temescal - Grand",
    TransportMode: "bus",
    PublicCode: "12",
    SiriLineRef: "12",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "701",
    Name: "Pittsburg/BP Transbay Early Bird",
    TransportMode: "bus",
    PublicCode: "701",
    SiriLineRef: "701",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "706",
    Name: "Bay Fair Transbay Early Bird",
    TransportMode: "bus",
    PublicCode: "706",
    SiriLineRef: "706",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "675",
    Name: "Korematsu - El Cerrito - Carlson",
    TransportMode: "bus",
    PublicCode: "675",
    SiriLineRef: "675",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "676",
    Name: "De Anza - Crespi - Rollingwood",
    TransportMode: "bus",
    PublicCode: "676",
    SiriLineRef: "676",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "677",
    Name: "Montera - Broadway Terrace",
    TransportMode: "bus",
    PublicCode: "677",
    SiriLineRef: "677",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "680",
    Name: "Bishop O'Dowd High - MacArthur",
    TransportMode: "bus",
    PublicCode: "680",
    SiriLineRef: "680",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "681",
    Name: "DeJean - Cutting - Macdonald",
    TransportMode: "bus",
    PublicCode: "681",
    SiriLineRef: "681",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "682",
    Name: "Bishop O'Dowd High - Montclair",
    TransportMode: "bus",
    PublicCode: "682",
    SiriLineRef: "682",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "684",
    Name: "El Cerrito - Arlington - Garvin",
    TransportMode: "bus",
    PublicCode: "684",
    SiriLineRef: "684",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "687",
    Name: "Lincoln Middle - Bay Farm",
    TransportMode: "bus",
    PublicCode: "687",
    SiriLineRef: "687",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "688",
    Name: "St. Mary's College - Montclair",
    TransportMode: "bus",
    PublicCode: "688",
    SiriLineRef: "688",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "696",
    Name: "Oakland Tech - Montclair",
    TransportMode: "bus",
    PublicCode: "696",
    SiriLineRef: "696",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "702",
    Name: "Pleas Hill Transbay Early Bird",
    TransportMode: "bus",
    PublicCode: "702",
    SiriLineRef: "702",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "70",
    Name: "Rheem - San Pablo Dam - Appian",
    TransportMode: "bus",
    PublicCode: "70",
    SiriLineRef: "70",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "72R",
    Name: "San Pablo Rapid",
    TransportMode: "bus",
    PublicCode: "72R",
    SiriLineRef: "72R",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "76",
    Name: "Hilltop - Market -  Cutting",
    TransportMode: "bus",
    PublicCode: "76",
    SiriLineRef: "76",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "78",
    Name: "Fruitvale Bart\\ Ferry Terminal",
    TransportMode: "bus",
    PublicCode: "78",
    SiriLineRef: "",
    Monitored: false,
    OperatorRef: "AC",
  },
  {
    Id: "E",
    Name: "Tunnel Rd. - Claremont Transbay",
    TransportMode: "bus",
    PublicCode: "E",
    SiriLineRef: "E",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "NX3",
    Name: "MacArthur - Eastmont Transbay",
    TransportMode: "bus",
    PublicCode: "NX3",
    SiriLineRef: "NX3",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "29",
    Name: "Hollis - Peralta - Lakeshore",
    TransportMode: "bus",
    PublicCode: "29",
    SiriLineRef: "29",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "OX",
    Name: "Bay Farm - Park St. Transbay",
    TransportMode: "bus",
    PublicCode: "OX",
    SiriLineRef: "OX",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "33",
    Name: "Piedmont - Harrison - Park Blvd.",
    TransportMode: "bus",
    PublicCode: "33",
    SiriLineRef: "33",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "36",
    Name: "Dwight - Shellmound - Adeline",
    TransportMode: "bus",
    PublicCode: "36",
    SiriLineRef: "36",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "79",
    Name: "Colusa - The Alameda - Claremont",
    TransportMode: "bus",
    PublicCode: "79",
    SiriLineRef: "79",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "96",
    Name: "Alameda Pt. - 14th Ave. - Dimond",
    TransportMode: "bus",
    PublicCode: "96",
    SiriLineRef: "96",
    Monitored: true,
    OperatorRef: "AC",
  },
  {
    Id: "28",
    Name: "Alvarado - Castro Valley - B St.",
    TransportMode: "bus",
    PublicCode: "28",
    SiriLineRef: "28",
    Monitored: true,
    OperatorRef: "AC",
  },
];

export default busLines;
