// let busLines2: Array<string>;

// busLines2 = [
//     'Mission - Decoto - Fremont Blvd.',
//     'University - College - Rockridge',
//     'Fremont Blvd. - Mission San Jose',
//     '35th Ave. - Merritt College',
//     'Broadway - Santa Clara',
//     'Seminary - Sobrante Park',
//     'Foothill - Eastmont All Nighter'
//     'Ashland - San Lorenzo - A St.',
//     'D St. - Maud - Fairview',
//     'Paseo Padre - Thornton - Cherry',
//     'Sacramento -  Christie Transbay',
//     'San Pablo Transbay',
//     Eastmont - 98th Ave. - Edgewater
//     Adeline - Market Transbay
//     40th St. - MacArthur
//     Sacramento - Market
//     Dimond - Fruitvale - Bay Farm
//     7th St. - San Antonio - 23rd Av.
//     Foothill - Bancroft - Bay Fair
//     Colusa - Solano Transbay
//     Grizzly Peak - Euclid
//     Arlington - 1000 Oaks - Shattuck
//     Macdonald - San Pablo
//     Hilltop - Pierce Transbay
//     Niles - Stevenson - NewPark
//     Grimmer - Warm Springs
//     Grand Lake - Laurel  Transbay
//     Cutting - North Richmond Nights
//     Skyline - Dimond - Fruitvale
//     Santa Clara - Encinal Transbay",
//     Piedmont - Oakland Ave. Transbay",
//     Stanford - Dumbarton - Fremont",
//     High - South Shore Transbay",
//     Rich - Oak Transbay All Nighter",
//     CSUEB - Southland - Chabot Coll",
//     14th St - San Antonio - High St",
//     Tilden Park - Spruce - Oxford",
//     San Pablo All Nighter",
//     College - Broadway All Nighter",
//     Montclair - Park Blvd. Transbay",
//     MacArthur Transbay Limited",
//     Fremont Blvd. - Pacific Commons",
//     Mission San Jose - Milpitas",
//     Solano - Shattuck - MLK Jr.",
//     Uptown Oakland\\ San Leandro BART Southbound OWL",
//     UC Village - Cedar - UC Campus",
//     Buena Vista - Fruitvale",
//     Decoto - Newark Blvd. - Mowry",
//     Dimond - Fruitvale - South Shore",
//     82nd Ave. - Grass Valley Limited",
//     Shattuck - University Transbay",
//     Osgood - Warm Springs - Landing",
//     Head Royce - Hebrew Day - Berk.",
//     Richmond High - Point Richmond",
//     Mission - Decoto - NewPark",
//     Head Royce - Montclair - College",
//     Head Royce - Piedmont",
//     Westlake Middle - 14th Ave.",
//     Skyline High - Seminary",
//     Montera - Skyline - 82nd Ave.",
//     Estudillo - Davis - Meekland",
//     Estudillo - Davis -  Lewelling",
//     Whitman - Huntwood - Union Landg",
//     Santa Clara - Weekes - Huntwood",
//     Skyline - Comm. Day - High St.",
//     Montera - Skyline - Grass Valley",
//     Berkeley - Telegraph - Oakland",
//     Montera - Oakmore - Seminary",
//     Skyline High - Elmhurst",
//     Montera - MacArthur",
//     Newark Jr. High - Cedar",
//     American High - Thornton Jr.",
//     Irvington High - Horner Jr. High",
//     Skyline High - 35th Ave.",
//     E. 14th St. - Mission",
//     Mission San Jose - Hopkins Jr.",
//     Washington - Centerville Jr.",
//     Newark Memorial - Newark Blvd.
//     Newark Memorial  - Cedar",
//     Newark Memorial - Cherry - Haley",
//     Encinal - Alameda - Bay Farm",
//     Skyline High - 73rd Ave.",
//     Montera - Montclair - Colton",
//     Montera - 35th Ave.",
//     Oak High - Oak Tech - MacArthur",
//     E 14th - Mission  All Nighter",
//     Winton - Industrial - Tennyson",
//     MacArthur - Airport All Nighter",
//     Parchester - Rumrill - Carlson",
//     San Pablo Dam - 23rd St.",
//     Hilltop - CCC - San Pablo",
//     85th Ave. - Elmhurst - 90th Ave.",
//     Hesperian - Alvarado - Decoto",
//     73rd Ave. - Coliseum - Airport",
//     Skyline - Bret Harte - MacArthur",
//     Montera - Broadway Terrace",
//     Skyline High - Broadway Terrace",
//     Encinal - South Shore - High St.",
//     Korematsu - E.C. - No. Richmond",
//     Crespi Middle - San Pablo Dam",
//     De Anza - Crespi - Fairmede",
//     Crespi - Hiltop - Broadway",
//     MLK Jr. - Temescal - Grand",
//     Pittsburg/BP Transbay Early Bird",
//     Bay Fair Transbay Early Bird",
//     Korematsu - El Cerrito - Carlson",
//     De Anza - Crespi - Rollingwood",
//     Montera - Broadway Terrace",
//     Bishop O'Dowd High - MacArthur",
//     DeJean - Cutting - Macdonald",
//     Bishop O'Dowd High - Montclair",
//     El Cerrito - Arlington - Garvin",
//     Lincoln Middle - Bay Farm",
//     St. Mary's College - Montclair",
//     Oakland Tech - Montclair",
//     Pleas Hill Transbay Early Bird",
//     Rheem - San Pablo Dam - Appian",
//     San Pablo Rapid",
//     Hilltop - Market -  Cutting",
//     Fruitvale Bart\\ Ferry Terminal",
//     Tunnel Rd. - Claremont Transbay",
//     MacArthur - Eastmont Transbay",
//     Hollis - Peralta - Lakeshore",
//     Bay Farm - Park St. Transbay",
//     Piedmont - Harrison - Park Blvd.",
//     Dwight - Shellmound - Adeline",
//     Colusa - The Alameda - Claremont",
//     Alameda Pt. - 14th Ave. - Dimond",
//     Alvarado - Castro Valley - B St.",

// ]
